version: '3.7'

services:
  elasticsearch:
    image: elasticsearch:7.17.24
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
    networks:
      - elk

  logstash:
    image: logstash:7.17.24
    ports:
      - "5044:5044"
    networks:
      - elk
    volumes:
      - "C:/campspring/logging/src/main/resources/logstash.conf:/usr/share/logstash/pipeline/logstash.conf"
      - "C:/campspring/logging/log/spring-boot-logger.log:/usr/share/logstash/log/spring-boot-logger.log"


  kibana:
    image: kibana:7.17.24
    ports:
      - "5601:5601"
    networks:
      - elk
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200



networks:
  elk:
    driver: bridge